name: disewainaja
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_core: ^3.8.0
  get_storage: ^2.1.1
  firebase_messaging: ^15.1.5
  google_fonts: ^6.2.1
  dio: ^5.7.0
  geolocator: ^13.0.2
  loading_animation_widget: ^1.3.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.10
  slider_button: ^2.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_location_marker: ^9.1.1
  map_launcher: ^3.5.0
  url_launcher: ^6.3.1
  dropdown_search: ^6.0.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
